Repository rsksmart/lumino-explorer, pull requests merged in 2021-02, with the labels that each got.

#16 Fixing web issues for production
  lumino-explorer-web/.gitignore
  lumino-explorer-web/src/containers/dashboard/DashboardContainer.jsx
  lumino-explorer-web/src/containers/headers/HeaderContainer.jsx
  lumino-explorer-web/src/containers/headers/logo-rif.svg
Labels: bug

#14 Update README.md fix start instructions
  lumino-explorer-web/README.md
Labels: documentation

#18 Feature/rlp 1008/updating docs
  lumino-explorer-api/README.md
  lumino-explorer-web/README.md
Labels: enhancement
